Added documentation for max image size
anchore/enterprise-docs pull request #266
Opened 2021-01-14 22:31 UTC by zburstein

Add documentation for feature https://github.com/anchore/anchore-engine/issues/786

Signed-off-by: Zane Burstein <zane.burstein@anchore.com>

2021-01-19 10:05 UTC, zhill commented
Updated PR base to merge into 3.0-dev instead of master

2021-01-19 10:06 UTC, zhill commented on content/docs/using/cli_usage/images/_index.md
> +As of v3.0, Anchore Enterprise can be configured to have a size limit for images being added for analysis. This is disabled by default, but can be configured through the configuration variable `max_c
Should the "value less than 0 disables" be "less than or equal to 0"?

2021-01-19 17:01 UTC, zburstein commented on content/docs/using/cli_usage/images/_index.md
> +As of v3.0, Anchore Enterprise can be configured to have a size limit for images being added for analysis. This is disabled by default, but can be configured through the configuration variable `max_c
No its set up so negative values disable the feature

2021-01-21 23:42 UTC, hev commented
@Btodhunter I feel like these docs needs details and support in the helm chart.

2021-01-25 18:26 UTC, zburstein commented
@hev Brady added it to the chart for 3.0 (https://github.com/anchore/anchore-charts/commit/55603fffb48457e6186b592e67eaef61088cbe45) and I have updated this PR with instructions on how to add it to helm

2021-01-29 17:47 UTC, dspalmer99 commented on content/docs/using/cli_usage/images/_index.md
> +The max size feature is disabled by default but can be enabled through the `max_compressed_image_size_mb` configuration variable, which represents the size limit in MB of the compressed image. Values
Will a 0 value be enforced and prevent users from adding any images?

2021-01-29 17:48 UTC, dspalmer99 commented on content/docs/using/cli_usage/images/_index.md
> +The max size feature is disabled by default but can be enabled through the `max_compressed_image_size_mb` configuration variable, which represents the size limit in MB of the compressed image. Values
Nit: There's a double space in "this  can"

2021-01-29 17:49 UTC, dspalmer99 commented on content/docs/using/cli_usage/images/_index.md
> +The max size feature is disabled by default but can be enabled through the `max_compressed_image_size_mb` configuration variable, which represents the size limit in MB of the compressed image. Values
Nit: "non-integer", not "non integer"

2021-01-29 17:51 UTC, dspalmer99 requested changes
Please specify what configuring a 0 value does. Otherwise looks good to me outside of a few minor grammatical nits.

2021-01-29 17:55 UTC, zburstein commented on content/docs/using/cli_usage/images/_index.md
> +The max size feature is disabled by default but can be enabled through the `max_compressed_image_size_mb` configuration variable, which represents the size limit in MB of the compressed image. Values
Yeah it will. I can specify that

2021-01-29 18:10 UTC, zburstein commented on content/docs/using/cli_usage/images/_index.md
> +The max size feature is disabled by default but can be enabled through the `max_compressed_image_size_mb` configuration variable, which represents the size limit in MB of the compressed image. Values
@dspalmer99 Updated

2021-01-29 20:51 UTC, dspalmer99 approved these changes

2021-01-29 20:52 UTC, merged