docs updates: 2.4 upgrade, add missing link
anchore/enterprise-docs pull request #269
Opened 2021-01-20 16:20 UTC by thinkmassive

Detailed instructions for the Helm chart repo migration are available in the anchore-charts repo, but without knowing this ahead of time most users will visit the Upgrade page of the Enterprise docs site. This update will direct them to the migration doc in the new charts repo.

Also added a missing link regarding image whitelist/blacklist.

2021-01-21 02:23 UTC, zhill requested changes
just a small change from engine -> enterprise, then we're good to merge. Thanks!

2021-01-21 02:23 UTC, zhill commented on content/docs/installation/upgrade/_index.md
> +The major change between 2.3.x and 2.4+ is that the Helm chart repo has moved from helm/stable to charts.anchore.io. To upgrade from a previous version of the chart, you will need to delete your prev
These docs are now Enterprise specific, so need to change "Anchore Engine" here to "Anchore Enterprise".

2021-01-21 15:16 UTC, thinkmassive commented on content/docs/installation/upgrade/_index.md
> +The major change between 2.3.x and 2.4+ is that the Helm chart repo has moved from helm/stable to charts.anchore.io. To upgrade from a previous version of the chart, you will need to delete your prev
Fixed, thanks @zhill

2021-03-09 00:03 UTC, zhill approved these changes

2021-03-09 00:03 UTC, merged