Anchorectl
anchore/enterprise-docs pull request #303
Opened 2021-06-02 17:30 UTC by dakaneye

2021-06-03 16:34 UTC, Toure requested changes

2021-06-03 16:34 UTC, Toure commented on content/docs/using/anchorectl_usage/_index.md
> +The AnchoreCTL Enterprise CLI provides a command line interface on top of the Anchore Enterprise & Engine REST APIs. AnchoreCTL is published as a Cobra-CLI Go Binary that can be installed from a publ
I think we probably want to pull any reference to Anchore engine as this tool is intended for Enterprise only. What's your thought?

2021-06-03 17:15 UTC, dakaneye commented on content/docs/using/anchorectl_usage/_index.md
> +The AnchoreCTL Enterprise CLI provides a command line interface on top of the Anchore Enterprise & Engine REST APIs. AnchoreCTL is published as a Cobra-CLI Go Binary that can be installed from a publ
@Toure I get it's intended for enterprise, but I think long term it will replace the anchore-cli right? @hev can you confirm?

It also has engine-functionality so that's why I kept the reference

2021-06-04 19:19 UTC, Toure approved these changes

2021-06-09 16:45 UTC, merged