Documentation for grype integration tech preview
anchore/enterprise-docs pull request #305
Opened 2021-06-14 14:47 UTC by dspalmer99

Engine docs updates for grype integration tech preview

2021-06-14 14:51 UTC, dspalmer99 commented
Also see the corresponding engine PR [here](https://github.com/anchore/anchore-engine/pull/1116.)

2021-06-22 14:24 UTC, Toure requested changes

2021-06-22 14:24 UTC, Toure commented on content/docs/grype/_index.md
> +and is strictly provided here so users can get start to use it and get a sense for the functionality. It may not include all of the
I think this part of the sentence may read better as followed:
"so users can get start to use it and get a sense for the functionality" -> "to allow the user to gain an early preview into the upcoming functionality."

2021-06-22 14:24 UTC, Toure commented on content/docs/grype/_index.md
> +
I would place a note under this section to indicate that downgrading from grype mode to legacy is not supported and will cause irreversible problems.

2021-06-22 14:24 UTC, Toure commented on content/docs/grype/_index.md
> +
line 17 has a small typo:

"ona" -> "on a"

2021-06-22 14:24 UTC, Toure commented on content/docs/overview/feeds/_index.md
> +here so users can get start to use it and get a sense for the functionality. It may not include all the functionality of the legacy scanner. Please report
I think this part of the sentence may read better as followed:
"so users can get start to use it and get a sense for the functionality" -> "to allow the user to gain an early preview into the upcoming functionality."

2021-06-22 15:02 UTC, dspalmer99 commented
Thanks @Toure! I've addressed all of that feedback.

2021-06-22 15:02 UTC, dspalmer99 commented on content/docs/grype/_index.md
> +
Done

2021-06-22 15:03 UTC, dspalmer99 commented on content/docs/grype/_index.md
> +and is strictly provided here so users can get start to use it and get a sense for the functionality. It may not include all of the
I took your suggestion, but then refactored it a little further. I definitely agree it was too informal before, but I think it is more concise now.

2021-06-22 15:03 UTC, dspalmer99 commented on content/docs/grype/_index.md
> +
Fixed.

2021-06-22 15:33 UTC, Toure approved these changes

2021-06-22 19:21 UTC, merged