Improves docs around Kubernetes Inventory UI
anchore/enterprise-docs pull request #306
Opened 2021-06-17 16:23 UTC by hev

This PR updates the docs related to Kubernetes UI and makes Kubernetes Inventory more prominent. Includes the following changes.

* Highlights KAI on homepage
* Adds Using Kubernetes Inventory section
* Cleans up the concepts page to focus on installing kai and moves embedded mode to sub-page.

Would still like to add screenshots to the using page.

2021-06-17 21:13 UTC, dakaneye commented
This probably needs to merge into 3.1-dev

2021-06-17 21:20 UTC, dakaneye requested changes

2021-06-17 21:20 UTC, dakaneye commented on content/_index.html
> -Install Anchore using the [Helm Chart](https://github.com/anchore/anchore-charts/blob/master/stable/anchore-engine) and make admission decisions based on analysis and policy-based evaluations with ou
not sure this should remove the reference to the actual Anchore Helm chart

2021-06-17 21:20 UTC, dakaneye commented on content/docs/overview/concepts/images/inventory/_index.md
> +    # Note: reccommend using the inventory-agent role
nit: typo

2021-06-17 21:20 UTC, dakaneye commented on content/docs/overview/concepts/images/inventory/_index.md
> +2. Run helm install in the cluster(s) you wish to track
nit: install "for" the cluster(s) you wish to track

2021-06-17 21:20 UTC, dakaneye commented on content/docs/overview/concepts/images/inventory/_index.md
> +Kai must be able to resolve the Anchore URL and requires API credentials. Review the kai logs if you are not able to see the inventory results in the UI.
external API and catalog service logs may also be consulted for troubleshooting purposes.

2021-06-17 21:20 UTC, dakaneye commented on content/docs/overview/concepts/images/inventory/_index.md
> +In addition to running as agent kai can also be run by Anchore Enterpise in an embedded mode. In this mode `kai` runs within the Anchore Enterprise, and needs a cluster configuration to access the Ku
within the Anchore Enterprise "container"

2021-06-17 21:20 UTC, dakaneye commented on content/docs/overview/concepts/images/inventory/_index.md
> +In addition to running as agent kai can also be run by Anchore Enterpise in an embedded mode. In this mode `kai` runs within the Anchore Enterprise, and needs a cluster configuration to access the Ku
requires "a" cluster

2021-06-17 21:20 UTC, dakaneye commented on content/docs/overview/concepts/images/inventory/_index.md
> +In situations where you may not be able to have consitent network connection `kai` along with the inventory API can be used to collect and report inventory back to Anchore Enterprise. Inventory colle
last sentence is a bit wordy: "We hope to support other types of container runtime inventory in the future"

2021-06-17 21:20 UTC, dakaneye commented on content/docs/overview/concepts/images/inventory/_index.md
> -Clusters may be retrieved in list format via HTTP GET on `/v1/enterprise/inventories/clusters` or by name, with HTTP GET on `v1/enterprise/inventories/clusters/<name>`
this bit seems to have not made it back into the embedded mode documentation

2021-06-17 21:20 UTC, dakaneye commented on content/docs/overview/concepts/images/inventory/_index.md
> -If `kai` does not find an image that was previously in the inventory, it waits for a configurable TTL to expire before removing that image:
this section appears to be missing in the new documentation version as well

2021-06-18 16:43 UTC, hev commented
Wrong branch. Closing.

2021-06-18 16:43 UTC, closed without merging