Adds Kubernetes Inventory UI
anchore/enterprise-docs pull request #308
Opened 2021-06-18 20:23 UTC by hev

This PR updates the docs related to Kubernetes UI and makes Kubernetes Inventory more prominent. Includes the following changes.

* Highlights KAI on homepage
* Adds Using Kubernetes Inventory section
* Cleans up the concepts page to focus on installing kai and moves embedded mode to sub-page.

Would still like to add screenshots to the using page but submitting as is for now.

2021-06-28 18:59 UTC, Toure requested changes
Just a small nit on one thing. But it looks good.

2021-06-28 18:59 UTC, Toure commented on content/docs/overview/concepts/images/inventory/_index.md
> +Anchore uses a go binary called [kai](https://github.com/anchore/kai) that leverages the [Kubernetes Go SDK](https://github.com/kubernetes/client-go) to reach out and list pods in a configurable set
nit: Kubernetes Go is a library, should we include it in the docs?

2021-06-29 00:26 UTC, zhill approved these changes
To facilitate quick updates I'll merge this and then resolve the refs myself since I'm not sure if ref or relref is the right recommendation without some testing. But generally, links should use the hugo content xrefs: https://gohugo.io/content-management/cross-references/ so that it will manage updates properly and fail compile if not found.

2021-06-29 00:26 UTC, zhill commented on content/docs/overview/concepts/images/inventory/_index.md
> +The most common way to track inventory is to install [`kai`](https://github.com/anchore/kai). as an agent in your cluster. To do this you will need to configure credentials
Typo with extra period after the link.
```suggestion
The most common way to track inventory is to install [`kai`](https://github.com/anchore/kai) as an agent in your cluster. To do this you will need to configure credentials
```

2021-06-29 00:26 UTC, zhill commented on content/_index.html
> +{{% blocks/feature svg="icons/kubernetes-logo.svg" href="/docs/using/ui_usage/kubernetes/" title="Kubernetes" %}}
This link will 404 in the built site.
```suggestion
{{% blocks/feature svg="icons/kubernetes-logo.svg" href="/current/docs/using/ui_usage/kubernetes" title="Kubernetes" %}}
```

2021-06-29 00:26 UTC, zhill commented on content/docs/using/ui_usage/kubernetes/_index.md
> +Anchore Enterprise allows you to navigate through your Kubernetes clusters to quickly and easy asses your vulnerabilites, apply policies, and take action on them. You'll need to configure your cluste
Ref update here as well

2021-06-29 00:26 UTC, zhill commented on content/docs/overview/concepts/images/inventory/_index.md
> +In addition to running as agent kai can also be run by Anchore Enterpise in an embedded mode. In this mode `kai` runs within the Anchore Enterprise, and needs a cluster configuration to access the Ku
Use content ref for link here
```suggestion
In addition to running as agent kai can also be run by Anchore Enterpise in an embedded mode. In this mode `kai` runs within the Anchore Enterprise, and needs a cluster configuration to access the Kubernetes API. This still requires cluster but allows for monitoring without the installation of additional components. See more details about setting up [embedded mode]({{< relref "embedded" >}}). 
```

2021-06-29 00:26 UTC, zhill commented on content/docs/overview/concepts/images/inventory/_index.md
> +For more details about watching clusters, and reviewing policy results see the [Using Kubernetes Inventory](/docs/using/ui_usage/kubernetes/) section.
Same here

2021-06-29 04:55 UTC, merged