Anchorectl changes
anchore/enterprise-docs pull request #309
Opened 2021-06-21 14:41 UTC by hev

This PR makes some small changes to the AnchoreCTL page to improve clarity. 

* Changes name from anchore-cli to anchorectl in the title and nav
* Adds a sentence about overlap of anchore-cli
* Updates version number

Also includes changes in #308

2021-06-28 18:52 UTC, Toure requested changes

2021-06-28 18:52 UTC, Toure commented on content/docs/installation/anchorectl/_index.md
Just curious as to why the versions have been downgraded?

2021-06-28 21:01 UTC, zhill requested changes
Overall looks good, but needs updates to the refs to use the template format so that, for example if they don't exist the hugo build will fail.

Also, since this updates some anchorectl download URLs, they need to all be consistent and reference 0.1.2. They are currently mixed in version.

2021-06-28 21:01 UTC, zhill commented on content/docs/overview/concepts/images/inventory/_index.md
> +In addition to running as agent kai can also be run by Anchore Enterpise in an embedded mode. In this mode `kai` runs within the Anchore Enterprise, and needs a cluster configuration to access the Ku
This link should use the template format to ensure proper resolution and checks in CI: `({{< ref "./embedded" >}})`

2021-06-28 21:01 UTC, zhill commented on content/docs/using/ui_usage/kubernetes/_index.md
> +Anchore Enterprise allows you to navigate through your Kubernetes clusters to quickly and easy asses your vulnerabilites, apply policies, and take action on them. You'll need to configure your cluste
Similar ref update here.

2021-06-29 03:28 UTC, zhill commented
> This PR makes some small changes to the AnchoreCTL page to improve clarity.
> 
> * Changes name from anchore-cli to anchorectl in the title and nav
> * Adds a sentence about overlap of anchore-cli
> * Updates version number
> 
> Also includes changes in #308

Should we close #308 then?

2021-06-29 04:55 UTC, zhill commented
I'm going to merge this and make updates myself after merge as part of other updates.

2021-06-29 04:55 UTC, merged