Release notes for 3.1.0 as well as some updates to other 3.1 docs content
anchore/enterprise-docs pull request #314
Opened 2021-06-29 11:11 UTC by zhill

2021-06-29 13:37 UTC, dspalmer99 approved these changes
A few typos, but overall this is looking good.

2021-06-29 13:37 UTC, dspalmer99 commented on content/docs/installation/anchorectl/_index.md
> +AnchoreCTL is published as simple binary that can be installed by downloading it or using provided packages for installation in different platforms.
a simple binary

2021-06-29 13:37 UTC, dspalmer99 commented on content/docs/overview/concepts/images/inventory/_index.md
>  The most common way to track inventory is to install [`kai`](https://github.com/anchore/kai). as an agent in your cluster. To do this you will need to configure credentials
There's an extra period at the end of [`kai`](https://github.com/anchore/kai).

2021-06-29 13:37 UTC, dspalmer99 commented on content/docs/releasenotes/3.1.0/_index.md
> +By default, the analyzer will filter packages that are determined by at analysis time to be "owned" by a parent package when that package
Small typo, extra "by" in "that are determined by at analysis"

2021-06-29 13:37 UTC, dspalmer99 commented on content/docs/releasenotes/3.1.0/_index.md
> +
Extra line break here

2021-06-29 13:37 UTC, dspalmer99 commented on content/docs/releasenotes/3.1.0/_index.md
> +
Extra line break here

2021-06-29 13:37 UTC, dspalmer99 commented on content/docs/releasenotes/3.1.0/v2_vulnerability_scanning.md
> +deployed feed service. In future releases, the Microsoft MSRC and VulnDB data soures will be supported as well
soures -> sources

2021-06-29 13:37 UTC, dspalmer99 commented on content/docs/using/ui_usage/kubernetes/_index.md
> +Another important aspect of the Kubernetes Inventory UI is the ability to assess how a vulnerability in a container images impacts your environment. For every container when you see a note about it u
bast-radius -> blast-radius

2021-06-29 13:37 UTC, dspalmer99 commented on content/docs/releasenotes/3.1.0/_index.md
> +## Enterprise UI Changes
Are these sections still forthcoming? Happy to take another look afterwards.

2021-06-29 13:37 UTC, dspalmer99 commented on content/docs/using/ui_usage/kubernetes/_index.md
> +The Kubernetes Inventory is only available for an Account's default policy. You may want to consider setting up an account specifically for tracking your Kubernetes Inventory and enforcing a policy.
There's a capitalization mismatch between the two uses of "account" in this paragraph.

2021-06-29 14:08 UTC, Toure requested changes

2021-06-29 14:08 UTC, Toure commented on content/docs/overview/concepts/images/inventory/_index.md
> +To quickly verify that you are tracking Kubernetes Inventory you can quickly access inventory results from the `anchorectl` with the  command `anchorectl inventory list`. The UI for the Kubernetes al
The second use of quickly could be removed as the initial use of quickly sets the intent for the sentence.

2021-06-29 17:07 UTC, dspalmer99 commented
Tested the changed curls, all worked correctly.

2021-06-30 00:01 UTC, zhill commented on content/docs/releasenotes/3.1.0/_index.md
> +## Enterprise UI Changes
Yes these will be updated by @holt with UI updates before publication

2021-06-30 00:02 UTC, zhill commented
Thanks for the reviews!

2021-06-30 00:03 UTC, merged