Update feed sync data configuration section
anchore/enterprise-docs pull request #348
Opened 2021-10-04 22:54 UTC by nightfurys

Signed-off-by: Swathi Gangisetty <swathi@anchore.com>

2021-10-04 23:27 UTC, anchoredeanlappi requested changes
Just a few minor edits. Thank you!

2021-10-04 23:27 UTC, anchoredeanlappi commented on content/docs/using/cli_usage/feeds/feed_configuration.md
> +further explained below.
```suggestion
and are explained in detail in the following sections.
```

2021-10-04 23:27 UTC, anchoredeanlappi commented on content/docs/using/cli_usage/feeds/feed_configuration.md
> +Note that the location and format of this config data changed slightly in Anchore Engine 0.10 to reflect some internal refactoring.  Ensure this config is synchronized between
```suggestion
Note: The location and format of the config data changed slightly in Anchore Engine 0.10 to reflect some internal refactoring.  Ensure this 
```

2021-10-04 23:27 UTC, anchoredeanlappi commented on content/docs/using/cli_usage/feeds/feed_configuration.md
> +The `grypedb` feed group syncs a single grype database to the policy engine.
```suggestion
The `grypedb` feed group syncs a single Grype database to the policy engine. 
```

2021-10-04 23:27 UTC, anchoredeanlappi commented on content/docs/using/cli_usage/feeds/feed_configuration.md
> +A grype database contains data spanning multiple groups. Due to this encapsulation, it is not possible to enable or disable individual feed groups
```suggestion
A Grype database contains data that spans multiple groups. Due to this encapsulation, it is not possible to enable or disable individual feed groups
```

2021-10-04 23:27 UTC, anchoredeanlappi commented on content/docs/using/cli_usage/feeds/feed_configuration.md
> +Anchore Enterprise will default to downloading the feed group from a publicly accessible url maintained by Grype https://toolbox-data.anchore.io/grype/databases/listing.json.
```suggestion
Anchore Enterprise will default to downloading the feed group from a publicly accessible URL maintained by Grype https://toolbox-data.anchore.io/grype/databases/listing.json. 
```

2021-10-04 23:27 UTC, anchoredeanlappi commented on content/docs/using/cli_usage/feeds/feed_configuration.md
> +The grype database available from this endpoint does not include third party/proprietary groups such as VulnDB and MSRC.
```suggestion
The Grype database available from this endpoint does not include third-party/proprietary groups such as VulnDB and MSRC. 
```

2021-10-04 23:27 UTC, anchoredeanlappi commented on content/docs/using/cli_usage/feeds/feed_configuration.md
> +us-west-2 region. This does not include third party/proprietary groups such as VulnDB and MSRC.
```suggestion
us-west-2 region. This does not include third-party/proprietary groups such as VulnDB and MSRC. 
```

2021-10-05 22:46 UTC, zhill approved these changes

2021-10-05 23:07 UTC, merged