Added release notes content for 3.3.0
anchore/enterprise-docs pull request #369
Opened 2021-11-19 16:18 UTC by anchoredeanlappi

Added 3.3.0 release notes.
Please review.
Dean

2021-11-19 17:11 UTC, emily-lopez approved these changes
Looks good to me

2021-11-22 17:20 UTC, nightfurys requested changes
@anchoredeanlappi Looks good overall. Only a few things missing in the change log and upgrade related docs. Feel free to ping me once they have been added and I'll update the review accordingly

2021-11-22 17:20 UTC, nightfurys commented on content/docs/releasenotes/330.md
> +- Inventory images were failing to parse properly, which caused scan failures. This issue has been fixed.
This should be a super set of engine + enterprise fixes, it's missing items for both. I'm going off of Jira filters set up by @emily-lopez, updated the component field to exclude UI. Please feel free to reword them as necessary. Links to Jira tickets for your reference, don't need to be included in the docs
- NuGet packages were not matched to vulnerabilities correctly [ENTERPRISE-865](https://anchore.atlassian.net/browse/ENTERPRISE-865) 
- Missing NVD CVSS scores in query vulnerabilities API with "grype" vulnerabilities provider [ENTERPRISE-755](https://anchore.atlassian.net/browse/ENTERPRISE-755)
- Remove invalid feed data "github:os" and "github:unknown" [ENTERPRISE-585](https://anchore.atlassian.net/browse/ENTERPRISE-585)

2021-11-22 17:20 UTC, nightfurys commented on content/docs/releasenotes/330.md
>  No database upgrades are required for this update.
This section needs to be updated. Here's a sample copied from a previous release notes

```
Upgrading to Anchore Enterprise 3.3.0 involves a database upgrade that the system will handle itself. It may cause the upgrade to take several minutes.

[Upgrading Anchore]({{< ref "/docs/installation/upgrade" >}})
```

2021-11-29 22:53 UTC, nightfurys approved these changes
Looks good! Thank you for making all the requested changes!!

2021-11-29 22:54 UTC, merged