Added known issue and updated anchorectl num
anchore/enterprise-docs pull request #375
Opened 2021-12-02 23:31 UTC by anchoredeanlappi

Added known issue information to 3.3.0 release notes.
Updated Anchorectl numbering.

Signed-off-by: anchoredeanlappi <88210304+anchoredeanlappi@users.noreply.github.com>

2021-12-02 23:47 UTC, nightfurys requested changes
Looks good overall, requesting a formatting change for code snippets

2021-12-02 23:47 UTC, nightfurys commented on content/docs/releasenotes/330.md
> +    % curl -u user:password "http://localhost:8228/v1/query/vulnerabilities?id=CVE-2019-15780"
Can this be formatted as a code snippet? Has to be enclosed within ```

2021-12-02 23:47 UTC, nightfurys commented on content/docs/releasenotes/330.md
> +    % curl -u user:password "http://localhost:8228/v1/query/vulnerabilities?id=CVE-2019-15780&namespace=nvd"
Can this be formatted as a code snippet? Has to be enclosed within ```

2021-12-03 00:06 UTC, nightfurys commented on content/docs/releasenotes/330.md
> +    % curl -u user:password "http://localhost:8228/v1/query/vulnerabilities?id=CVE-2019-15780"
@anchoredeanlappi looks like spaces have a similar effect, retracting my request here

2021-12-03 00:06 UTC, nightfurys commented on content/docs/releasenotes/330.md
> +    % curl -u user:password "http://localhost:8228/v1/query/vulnerabilities?id=CVE-2019-15780&namespace=nvd"
@anchoredeanlappi looks like spaces have a similar effect, retracting my request here

2021-12-03 00:07 UTC, nightfurys commented
Nice work on the change log! Can you also update _index.md file and add all the missing links?

2021-12-03 00:35 UTC, zhill requested changes
Suggestions on the wording to make the initial summary more clear to users so they don't have to read the whole detail to understand if it impacts them or not.

2021-12-03 00:35 UTC, zhill commented on content/docs/releasenotes/330.md
> +NVD CVSS scores are missing in the query vulnerabilities API with the Grype provider.
I'd like to be much more specific about this and indicate there is a workaround here, so folks don't have to read down the whole item to see that.
```suggestion
NVD CVSS scores may not be present in the API responses for the request to get detailed information query about a vulnerability feed record. 
* There is a workaround to get this information, see below for more detail on the workaround.
* This is only present for a subset of records NVD records.
* It does not impact the vulnerability reports or findings for images. It only impacts the next-gen vulnerability scanner so users still on the legacy scanner are not impacted.
```

2021-12-03 00:35 UTC, zhill commented on content/docs/releasenotes/330.md
> +#### Problem
```suggestion
#### Detail
```

2021-12-03 00:36 UTC, anchoredeanlappi commented on content/docs/releasenotes/330.md
> +NVD CVSS scores are missing in the query vulnerabilities API with the Grype provider.
Good point. I will add it

2021-12-03 00:46 UTC, zhill approved these changes
lgtm!

2021-12-03 00:50 UTC, merged